// ─────────────────────────────────────────────────────────────
//  INVOICE CONFIG — পুরো ইনভয়েসের লোগো, ঠিকানা, টেক্সট, রঙ ও
//  লেআউট শুধু এই একটি ফাইল থেকেই বদলানো যাবে।
// ─────────────────────────────────────────────────────────────
import logo from "@/assets/growvibe-logo.png";

/** লোগো বদলাতে চাইলে শুধু উপরের import পাথ বদলান (src/assets/…) */
export const LOGO_SRC: string = logo;

/** কোম্পানির তথ্য */
export const COMPANY = {
  name: "GrowVibe Ads Solution",
  tagline: "Facebook Ads & Digital Marketing Agency",
  address: "House 00, Road 00, Dhaka 1200, Bangladesh",
  phone: "+880 1XXX-XXXXXX",
  email: "billing@growvibe.com",
  website: "www.growvibe.com",
  /** ফুটারে দেখানো ধন্যবাদ লাইন */
  footerNote: "Thank you for your business.",
  /** ব্যাংক / পেমেন্ট তথ্য — খালি রাখলে দেখাবে না */
  paymentInfo: "",
};

/** ইনভয়েসের ডিফল্ট USD → BDT রেট (ক্লায়েন্টের নিজস্ব রেট থাকলে সেটাই অগ্রাধিকার পাবে) */
export const DEFAULT_USD_RATE = 122;

/** ইনভয়েস নম্বর ফরম্যাট — INV-000001 */
export const INVOICE_NO = {
  prefix: "INV-",
  padding: 6,
};

/** সব লেখা/লেবেল — বাংলা করতে চাইলে এখানেই বদলান */
export const LABELS = {
  documentTitle: "INVOICE",
  billTo: "Bill To",
  amountDue: "Amount Due",
  invoiceNo: "No",
  date: "Date",
  dueDate: "Due",
  rate: "Rate",
  mobile: "Mobile",
  email: "Email",
  description: "Description",
  qty: "Qty",
  unitRate: "Rate (USD)",
  amountUsd: "Amount (USD)",
  amountBdt: "Amount (BDT)",
  defaultLineItem: "Total Budget (Advertising Service)",
  totalBudget: "Total Budget",
  totalPaid: "Total Paid",
  totalDue: "Total Due",
  paidInFull: "PAID IN FULL — No due",
  notes: "Notes",
  paymentInfo: "Payment Info",
  generatedBy: "Generated by",
  signature: "Authorized Signature",
  status: { paid: "Paid", partial: "Partial", due: "Unpaid / Due" },
};

/** কোন কোন অংশ দেখাবে + মাপ — লেআউট কাস্টমাইজ */
export const LAYOUT = {
  showLogoHeader: true,
  showLogoFooter: true,
  showTagline: true,
  showRateLine: true,
  showAmountDueBox: true,
  showItemsTable: true,
  showBdtColumn: true,
  showStatusBadge: true,
  showSignature: true,
  showGeneratedBy: true,
  showTimestamp: true,
  /** px মাপ */
  logoHeaderHeight: 56,
  logoFooterHeight: 32,
  sheetMaxWidth: 820,
  sheetPadding: 40,
  baseFontSize: 13,
};

/** রঙ (যেকোনো CSS color) */
export const THEME = {
  accent: "#0f172a", // হেডার বর্ডার, টেবিল হেড, টোটাল সারি
  accentText: "#ffffff",
  text: "#1e293b",
  muted: "#64748b",
  faint: "#94a3b8",
  line: "#e2e8f0",
  boxBg: "#f8fafc",
  paid: "#059669",
  partial: "#d97706",
  due: "#dc2626",
};

/** স্ট্যাটাস ব্যাজের রঙ (bg / text / border) */
export const STATUS_STYLE = {
  paid: {
    bg: "rgba(5,150,105,0.12)",
    color: THEME.paid,
    border: "rgba(5,150,105,0.35)",
  },
  partial: {
    bg: "rgba(217,119,6,0.12)",
    color: THEME.partial,
    border: "rgba(217,119,6,0.35)",
  },
  due: {
    bg: "rgba(220,38,38,0.12)",
    color: THEME.due,
    border: "rgba(220,38,38,0.35)",
  },
} as const;

/** PDF ডাউনলোড সেটিংস */
export const PDF = {
  /** ফাইলের নাম: Invoice-INV-000001-Client.pdf */
  fileName: (invoiceNo: string, clientName: string) =>
    `Invoice-${invoiceNo}-${clientName.replace(/[^\w\u0980-\u09FF]+/g, "_")}.pdf`,
  pageSize: "a4" as const,
  orientation: "portrait" as const,
  /** রেন্ডার শার্পনেস (2 = রেটিনা মানের) */
  scale: 2,
  marginMm: 8,
};
